### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by Moritz448** [illiliti/king#2]
I would recommend to change the license from Mit to GPL.
FOR RICHARD STALLMAN

**Comment by Moritz448** [comment]
BTW i would recommend using gPac https://github.com/luis-07/gpac

**Comment by illiliti** [comment]
I prefer permissive license for libraries and GPL for standalone software. king can be used as library, that's   one of the reasons why i chose MIT.

**Comment by luis-07** [comment]
But now someone can fork it and make it proprietary

**Comment by Moritz448** [comment]
Oh lets do that
I would name it queen.
But i recommend using gPac anyways.
