### ISSUE TITLE
Is this still kiss?

### ISSUE THREAD

**Issue by 9glenda** [illiliti/king#3]
I don’t know but one of the Main reasons I like to use kiss is because it’s small Codebase.

**Comment by 9glenda** [comment]
I mean it has a lot of nice new features don’t understand me wrong but I really like the small codebase.

**Comment by Moritz448** [comment]
I like the bloat in the kiss codebase

**Comment by 9glenda** [comment]
Maybe you should brand KING as an feature rich kiss

**Comment by illiliti** [comment]
King doesn't adhere to kiss goals. If kiss is simple and portable, king may take a different path.
